name: markdown

on:
  workflow_call:
    inputs:
      lint-config:
        type: string
        required: false
        default: 'configs/md_lint_config.yml'
        description: Path to markdownlint config file (JSON, JSONC, or YML).
      link-check-config:
        type: string
        required: false
        default: 'configs/mlc_config.json'
        description: Path to markdown link check config file (JSON).

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout infra-library repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: soumeh01/infra-library
          path: 'infra-library'

      - name: Register markdownlint matcher
        run: |
          echo "::add-matcher::infra-library/configs/markdownlint.json"

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: 'code-repository'

      - name: Determine lint config path
        run: |
          if [ "${{ inputs.lint-config }}" = "configs/md_lint_config.yml" ]; then
            echo "CONFIG_PATH=infra-library/${{ inputs.lint-config }}" >> $GITHUB_ENV
          else
            echo "CONFIG_PATH=code-repository/${{ inputs.lint-config }}" >> $GITHUB_ENV
          fi

      - name: Run markdownlint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: '**/*.md'
          config: ${{ env.CONFIG_PATH }}
          ignore: 'code-repository/third_party_licenses.md'

      - name: Cleanup markdownlint matcher
        if: always()
        run: |
          echo "::remove-matcher owner=markdownlint::"

  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check markdown links
        uses: tcort/github-action-markdown-link-check@a800ad5f1c35bf61987946fd31c15726a1c9f2ba # v1.1.0
        with:
          use-verbose-mode: 'yes'
          base-branch: ${{ github.base_ref }}
          config-file: ${{ inputs.link-check-config }}
